services:
  k6:
    image: grafana/k6
    container_name: k6
    volumes:
      - ./scripts:/scripts
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - VUS=${VUS}
      - DURATION=${DURATION}
      - AMOUNT=${AMOUNT}
    command: ["run", "/scripts/test.js"]
